#===============================================================
#
# PERSONAL $HOME/.bash_aliases FILE for 
# GNU bash, version 5.1.0(2)-release (x86_64-pc-linux-gnu)
#
# Last modified: Wed 02 Oct 2024 05:41:01 AM CDT 
#
# This file is read (normally) by interactive shells only.
# Here is the place to define your aliases, functions and
# other interactive features like your prompt.
#
#==============================================================

alias ls='ls --color=always'
alias l='ls -lhF --group-directories-first'
alias lr='ls -R'
alias la='l -a'
alias grep='grep --color=always'
alias md='mkdir'
alias df='df -H'
alias pview='ristretto'
alias qu='sed -E'
alias can='cat -nbsv'
alias cant='cat -n'
alias sql3='sqlite3 $HOME/db/music.db'
alias fmu='find /run/media/brian/da8a7464-b3e2-4de2-8bf6-7c9951aa3ade/brian/music_store/music-lib/ -iname'
alias msql="sqlite3 ~/db/music.db \"select format('%s : %d - %s : %0d.%02d. %s', artist, year, album, disc, track, title) from cash;\""
alias test='ls'

