  POINTER_AND_OPERATOR_WITH_TYPE=' --POINTER_AND_OPERATOR_WITH_TYPE   "int *x --> int* x"'
POINTER_AND_OPERATOR_WITH_SYMBOL=' --POINTER_AND_OPERATOR_WITH_SYMBOL "int* x --> int *x"'
         SPACE_BEFORE_OPEN_PAREN=' --SPACE_BEFORE_OPEN_PAREN          "int foo(int x) --> int foo (int x)"'
      NO_SPACE_BEFORE_OPEN_PAREN=' --NO_SPACE_BEFORE_OPEN_PAREN       "int foo (int x) --> int foo(int x)"'

SPACE_AFTER_OPEN_PAREN_SPACE_BEFORE_CLOSE_PAREN='int foo (int x) --> int foo( int x )'

echo "$POINTER_AND_OPERATOR_WITH_TYPE"
echo "$POINTER_AND_OPERATOR_WITH_SYMBOL"
echo "$SPACE_BEFORE_OPEN_PAREN"
echo "$NO_SPACE_BEFORE_OPEN_PAREN"
